# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

// почитать составление правильного Запроса JSON почитать

POST http://localhost:8080/pet
Content-Type: application/json

{
  "category": {
    "name": "string"
  },
  "name": "Tobby",
  "tags": [
    {"name": "string1"},
    {"name": "string2"},
    {"name": "string3"}
  ],
  "petStatus": "AVAILABLE"
}

###

GET http://localhost:8080/pet/id

###

POST http://localhost:8080/store/order
Content-Type: application/json

{
"petId": 2,
"quantity":5,
"shipDate": "2021-03-01T17:00:31.618Z",
"oerderStatus": "APPROVED",
"userId": 333,
"complete": true

}

###

GET http://localhost:8080/store/order/3

###

DELETE http://localhost:8080/store/order/1

###

POST http://localhost:8080/store/category
Content-Type: application/json

{
  "name": "Toby"
}

###

GET http://localhost:8080/store/inventory

###

POST http://localhost:8080/store/user
Content-Type: application/json

{
  "id": 2,
  "userName": "Dima",
  "userStatus": "ADMIN"
  }

###

GET http://localhost:8080/user/2
Content-Type: application/json

###

GET http://localhost:8080/user/2
X-Key:
X-Status:

###


